server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: flight-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/airports/**
            - Path=/api/v1/flights/**
        - id: crew-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/crew-members/**
            - Path=/api/v1/crew-assignments/**
        - id: operations-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/operations/**
            - Path=/api/v1/audit-records/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
