apiVersion: v1
kind: Service
metadata:
  name: crew-service
  namespace: airline-operations
spec:
  selector:
    app: crew-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
