apiVersion: v1
kind: Service
metadata:
  name: flight-service
  namespace: airline-operations
spec:
  selector:
    app: flight-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
